Creating theme-switch (V1.0)
TUMQuantumClub/map-frontend pull request #9
Opened 2024-05-29 22:10 UTC by Lemonatix

First attempt of adding a working theme-switch for the app.

2024-05-31 12:03 UTC, biosfood requested changes
Seems good in gerneral, I left some notes for the code style

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +// MyApp = stateful widget, that maintains current theme state
remove this, this seems clear

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +    }
spacing

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +                        }
Indentation and semicolon, or remove brackets

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +// theme-switch (1.0) as .dart file
in lib folder, maybe UI or settings folder
remove 1.0 from file name and comment
remove comment

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +void main() {
no main function other than in main.dart or libs

2024-05-31 12:03 UTC, biosfood commented on theme-switch/theme-switch-dependences.yml
> +dependencies:
not in a separate file

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +    _loadTheme() async {
maybe just wait for this when booting?

Maybe profile this on some devices and only show the scene when everything is loaded

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +                child: SwitchListTile( // Allows user to toggle theme, which updates the state and saves the preference
Put this in a burger or side bar

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +    // _saveTheme Method: asynchronously saves theme preference to when changed
spacing

2024-05-31 12:03 UTC, biosfood commented on theme-switch/main-theme-switch (V1.0).dart
> +        _SharedPreferences prefs = await SharedPreferences.getInstance();
use a global SharedPreferences object
This lets us avoid waiting here again

2024-05-31 12:03 UTC, biosfood commented on theme-switch/theme-switch-dependences.yml
> +  shared_preference: ^2.0.13
Is this the right choice?
Some others maybe chime in here:
Is this enough for our storage needs or do we also need another storage?

2024-06-01 20:21 UTC, Lemonatix commented on theme-switch/main-theme-switch (V1.0).dart
> +// MyApp = stateful widget, that maintains current theme state
Is removed now

2024-06-01 20:22 UTC, Lemonatix commented on theme-switch/main-theme-switch (V1.0).dart
> +void main() {
main.dart is now consisting of the switch selector code

2024-06-01 20:23 UTC, Lemonatix commented on theme-switch/main-theme-switch (V1.0).dart
> +    _loadTheme() async {
Still need to figure out, how to test it with apple device

2024-06-01 20:23 UTC, Lemonatix commented on theme-switch/main-theme-switch (V1.0).dart
> +                child: SwitchListTile( // Allows user to toggle theme, which updates the state and saves the preference
Added Drawer (some kind of side bar)

2024-06-01 20:24 UTC, Lemonatix commented on theme-switch/main-theme-switch (V1.0).dart
> +        _SharedPreferences prefs = await SharedPreferences.getInstance();
Added a new ShapedPreferences object in main.dart

2024-06-02 14:04 UTC, biosfood requested changes
Organization is good now,
There are still a bunch of compiler warnings and some formatting errors that need fixing

Also, make sure to test everything

2024-06-02 14:04 UTC, biosfood commented on lib/main.dart
> +    });
still an indentation problem here

2024-06-02 14:04 UTC, biosfood commented on lib/main.dart
> +SharedPreferences? prefs;
I would call this preferences

2024-06-02 14:04 UTC, biosfood commented on lib/main.dart
> +                                         _saveTheme(value);
indentation

2024-06-02 14:04 UTC, biosfood commented on lib/main.dart
> +                drawer: Drawer(
Great. I like it

2024-06-02 14:04 UTC, biosfood commented on pubspec.yaml
> +  shared_preference: ^2.0.13
shared_preferences

2024-06-02 14:04 UTC, biosfood commented on lib/main.dart
> +    prefs = await SharedPreferences.getInstance();
I would prefer this to happen in the app but flutter seems to handle a loading screen quite nicely so this is okay for now

2024-06-02 14:06 UTC, biosfood commented
Also, commits can and should consist of a single "action", you don't need a new commit for every single change.
Doesn't matter now, we can just squash everything in the end

2024-06-02 21:53 UTC, biosfood commented on pubspec.yaml
> +  shared_preference: ^2.0.13
looks good now

2024-06-24 10:11 UTC, Lemonatix commented on theme-switch/theme-switch-dependences.yml
> +  shared_preference: ^2.0.13
Going with this for now

2024-06-24 10:19 UTC, biosfood approved these changes
Looks good now.
Great job
:)

2024-06-24 10:27 UTC, merged